### ISSUE TITLE
README information requirements

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/heart_rate_sentinel_server#1]
Other than the vcm hostname and port, what other information do you need in the readme in order to run the code/ be able to perform requests to the server? I figured since I would have the server running on the VCM, any other user wouldn't necessarily need anything else except a platform to send GET and POST requests

**Comment by dward2** [comment]
In the readme.md file, I would put in a brief description of the code files that you put in GitHub.  Let us know which file you would run to start your server.  Let us know which one runs a "client" program that you used to test your server.  This way, if there is a problem with your vitual machine, we can at least look at your code and perhaps run it on our own machine for testing.  We hope that won't be necessary, but if there is a problem with your VM, that would be our backup approach.
